namespace udpkit.plataform.photon.puncher
{
	internal enum StunMsgType
	{
		STUN_BINDING_REQUEST = 1,
		STUN_BINDING_RESPONSE = 257,
		STUN_BINDING_ERROR_RESPONSE = 273,
		STUN_BINDING_INDICATION = 17,
		STUN_SHARED_SECRET_REQUEST = 2,
		STUN_SHARED_SECRET_RESPONSE = 258,
		STUN_SHARED_SECRET_ERROR_RESPONSE = 274,
		STUN_ALLOCATE_REQUEST = 3,
		STUN_ALLOCATE_RESPONSE = 259,
		STUN_ALLOCATE_ERROR_RESPONSE = 275,
		STUN_REFRESH_REQUEST = 4,
		STUN_REFRESH_RESPONSE = 260,
		STUN_REFRESH_ERROR_RESPONSE = 276,
		STUN_SEND_INDICATION = 22,
		STUN_DATA_INDICATION = 23,
		STUN_CREATE_PERM_REQUEST = 8,
		STUN_CREATE_PERM_RESPONSE = 264,
		STUN_CREATE_PERM_ERROR_RESPONSE = 280,
		STUN_CHANNEL_BIND_REQUEST = 9,
		STUN_CHANNEL_BIND_RESPONSE = 265,
		STUN_CHANNEL_BIND_ERROR_RESPONSE = 281,
		STUN_CONNECT_REQUEST = 10,
		STUN_CONNECT_RESPONSE = 266,
		STUN_CONNECT_ERROR_RESPONSE = 282,
		STUN_CONNECTION_BIND_REQUEST = 11,
		STUN_CONNECTION_BIND_RESPONSE = 267,
		STUN_CONNECTION_BIND_ERROR_RESPONSE = 283,
		STUN_CONNECTION_ATTEMPT_REQUEST = 12,
		STUN_CONNECTION_ATTEMPT_RESPONSE = 268,
		STUN_CONNECTION_ATTEMPT_ERROR_RESPONSE = 284
	}
}
