public enum AchievementType
{
	None = 0,
	ReachPlayerLevel = 1,
	AcquireCharacter = 2,
	OwnCharacters = 3,
	EvolveCharacter = 4,
	ReachCharacterLevel = 5,
	AcquireMove = 6,
	UpgradeMove = 7,
	AcquireCatalyst = 8,
	AcquireCurrency = 9,
	OpenGacha = 10,
	PurchaseSkillNode = 11,
	MaxSkillTree = 12,
	UpgradeMarqueeAbility = 13,
	CompleteDeployment = 14,
	CompleteAct = 15,
	CompleteMatch = 16,
	CompleteMatchChallenge = 17,
	AchievePrizeFightResult = 18,
	DefendAgainstPrizeFightOpponent = 19,
	AttainPrizeFightStreak = 20,
	AchieveRiftBattleResult = 21,
	AttainRiftBattleStreak = 22,
	Combat = 23
}
