public enum AnimationHintType
{
	ANIM_HINT_NONE = 0,
	ANIM_HINT_TRIP = 1,
	ANIM_HINT_SPRAWL = 2,
	ANIM_HINT_KNOCKDOWN = 3,
	ANIM_HINT_HIGH_HIT = 4,
	ANIM_HINT_MID_HIT = 5,
	ANIM_HINT_LOW_HIT = 6,
	ANIM_HINT_FLOORBOUNCE = 7,
	ANIM_HINT_WALLBOUNCE = 8,
	ANIM_HINT_FLOORSLIDE = 9,
	ANIM_HINT_CRUMPLE = 10,
	ANIM_HINT_STAGGER = 11,
	ANIM_HINT_SNAP_OUT_A1 = 12,
	ANIM_HINT_SNAP_OUT_A2 = 13,
	ANIM_HINT_TECHABLE_SPRAWL = 14,
	ANIM_HINT_TECHABLE_KNOCKDOWN = 15,
	ANIM_HINT_KNOCKBACK = 16,
	ANIM_HINT_WALLSPLAT = 17,
	ANIM_HINT_LAUNCHER = 18,
	ANIM_HINT_FREEZE = 19,
	ANIM_HINT_NO_OTG_FLOORSLIDE = 20
}
