public enum ArtMemoryType : byte
{
	ARTMEM_UNKNOWN = 0,
	ARTMEM_LAST_POINT_CHAR_FRAME = 1,
	ARTMEM_INTRO_WIN = 2,
	ARTMEM_ASSIST_FRAMES = 3,
	ARTMEM_POINT_CHAR = 4,
	ARTMEM_ALWAYS_LOADED = 5,
	ARTMEM_8BIT_FRAMES = 6,
	ARTMEM_MAX = 7
}
