public enum CameraShakeType
{
	CAMERA_SHAKE_NONE = 0,
	CAMERA_SHAKE_LIGHT = 1,
	CAMERA_SHAKE_MED = 2,
	CAMERA_SHAKE_HARD = 3,
	CAMERA_SHAKE_TINY = 4,
	CAMERA_SHAKE_SUPER_HARD = 5,
	CAMERA_SHAKE_ULTRA_HARD = 6,
	CAMERA_SHAKE_EXTRA_TINY = 7,
	CAMERA_SHAKE_ALMOST_ULTRA_HARD = 8,
	CAMERA_SHAKE_INFINITESIMAL = 9
}
