public enum CoordType : byte
{
	COORD_MOVE_WITH_STAGE = 0,
	COORD_MOVE_WITH_PARENT = 1,
	COORD_MOVE_WITH_PARENT_THROWVICTIM = 2,
	COORD_MOVE_WITH_SCREEN = 3,
	COORD_LEADER_VISIBLE_PIXEL = 4,
	COORD_ATTACKER_VISIBLE_PIXEL = 5,
	COORD_LEADER_TOP_HALF = 6,
	COORD_MOVE_WITH_LEADER_TETHER_POINT = 7,
	COORD_MOVE_WITH_PARENT_TETHER_POINT = 8,
	COORD_MOVE_WITH_POINT_CHAR = 9,
	COORD_MOVE_WITH_ATTACKER = 10,
	COORD_MOVE_WITH_ATTACKER_TETHER_POINT = 11
}
