public enum HitType
{
	HIT_NONE = 0,
	HIT_HIGH = 1,
	HIT_LOW = 2,
	HIT_MID = 3,
	HIT_GRAB = 4,
	HIT_ALWAYS_CONNECTS = 16,
	HIT_PROJECTILE = 32,
	HIT_ALL_TYPES = 23,
	HIT_GRABS_AND_MIDS = 7,
	HIT_PASS_THROUGH_VICTIMS = 64,
	HIT_RENDER_THROW_VICTIM_IN_FRONT_OF_ME = 128
}
