public enum ZButtonState : byte
{
	PRESSED = 0,
	RELEASED = 1,
	CHANGED = 2,
	IS_DOWN = 3,
	IS_UP = 4,
	MATCH_ALL_EXCEPT_PRESSED = 5,
	MATCH_ALL_EXCEPT_RELEASED = 6,
	MATCH_ALL_EXCEPT_CHANGED = 7,
	MATCH_ALL_EXCEPT_IS_DOWN = 8,
	MATCH_ALL_EXCEPT_IS_UP = 9,
	ANY_STATE = 10
}
