namespace UnityEngine.UDP
{
	public enum LicensingErrorCode
	{
		ERROR_INVALID_PACKAGE_NAME = 0,
		ERROR_NON_MATCHING_UID = 1,
		ERROR_NOT_MARKET_MANAGED = 2,
		ERROR_CHECK_IN_PROGRESS = 3,
		ERROR_INVALID_PUBLIC_KEY = 4,
		ERROR_MISSING_PERMISSION = 5
	}
}
